### PR TITLE
Add scss to the webpack build

### PR DESCRIPTION
**Pull request by SheepFromHeaven**
If we are want to build single modules which we can import at one single point, we should allow importing of scss in ts/js files.

### CODE REVIEW

**Comment by timomayer** [comment]
@SheepFromHeaven can you please fix the conflicts?

**Comment by janrembold** [comment]
@SheepFromHeaven Any plans to update/discuss this topic?

**Comment by SheepFromHeaven** [comment]
Resolved ;)

**Comment by SheepFromHeaven** [comment]
@timomayer @janrembold any new here ;)?

**Comment by SheepFromHeaven** [comment]
@janrembold done

**Pull request merged**
