### PR TITLE
make host configurable

### PR DESCRIPTION
**Pull request by jurekbarth**
I've added the possibility to change the hostname of the connect server. That change make it easier to run biotope development with a docker backend.

### CODE REVIEW

**Comment by adrianfella** [comment]
Not necessarily, this can be used to avoid CORS issues (with e.g. APIs) while working in your local dev enviroment

**Comment by timomayer** [comment]
Not sure if i like the idea. In my oppinion API and Frontend should always have different (sub)domains and not be delivered over one domain. for example (cms.domain.tld for the headless cms, domain.tld for the frontend) this means you need CORS anyways and it is better to add and test it to your dev environment too.

**Comment by adrianfella** [comment]
This separation can also be achived with ports within the same domain, which is also a common concept, this PR makes biotope a lot easier to use for this architecture

**Comment by timomayer** [comment]
for ports you also need CORS.
for me it is ok to merge it. my antipathy comes from the goal to seperate biotope and the real application-frontend in the future and therefore all this configuration options we added to biotope are not needed anymore

**Comment by jurekbarth** [comment]
My picture of why this would be helpful is different. If your setup includes a reverse proxy, API and Frontend could live under the same domain. With that in mind it would make development easier with this addition.
I can agree, that when they're living under different domains you should not use this feature to circumvent CORS.
Does this make sense for you?

**Pull request merged**
